#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Registry references ONLY, never Framework schema/model emission."""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/schema/normalize"))
import additional_settings_policy  # noqa: E402 -- standalone script search path


def generate(directory):
    policies = json.loads(
        (ROOT / "internal/catalog/additional-settings.json").read_text()
    )
    if policies != additional_settings_policy.policies():
        raise ValueError("unreviewed additional settings registry policy")
    names = [p["resource_name"] for p in policies]
    if len(names) != len(set(names)):
        raise ValueError("duplicate additional settings canonical identity")
    rows = []
    for p in policies:
        if p["lifecycle"] != "singleton":
            raise ValueError("unreviewed additional settings lifecycle binding")
        functions = re.findall(
            r"func (\w+ResourceSchema)\(ctx context.Context\) schema.Schema",
            (directory / (p["resource_name"] + "_resource_gen.go")).read_text(),
        )
        if len(functions) != 1:
            raise ValueError("missing/ambiguous official generated schema")
        rows.append(
            "  " + json.dumps(p["resource_name"]) + ": generated." + functions[0] + ","
        )
    return (
        """// Code generated by tools/schema/additional_settings_bindings.py; DO NOT EDIT.
// Registry references only: all schemas/models come from the official generators.
// SPDX-License-Identifier: MPL-2.0
package provider
import (
 "context"
 "github.com/hashicorp/terraform-plugin-framework/resource"
 "github.com/hashicorp/terraform-plugin-framework/resource/schema"
 "github.com/matejaputic/terraform-provider-routeros/internal/catalog"
 "github.com/matejaputic/terraform-provider-routeros/internal/generated"
)
func additionalSettingsConstructors() []func()resource.Resource {
 bindings:=map[string]func(context.Context)schema.Schema{
"""
        + "\n".join(rows)
        + """
 }
 result:=[]func()resource.Resource{}
 for _,policy:=range catalog.AdditionalSettings(){
  result=append(result,func()resource.Resource{return newSingleton(policy,bindings[policy.Name](context.Background()))})
 }
 return result
}
"""
    )


if __name__ == "__main__":
    try:
        Path(sys.argv[2]).write_text(generate(Path(sys.argv[1])))
    except (OSError, ValueError, IndexError) as e:
        raise SystemExit("Additional settings binding failure: " + str(e)) from e
