#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Bind reviewed maintained lifecycles to OFFICIAL generated schema functions.

This emits only a registry of function references. It does not emit Framework
schemas, attributes, models, validators or lifecycle code. File/spec gates must
pass first. Inventory and the planning ledger never authorize a binding.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def generate(directory):
    policies = json.loads(
        (ROOT / "internal/catalog/extended-collections.json").read_text()
    )
    names = [p["resource_name"] for p in policies]
    if len(names) != 86 or len(set(names)) != 86:
        raise ValueError("reviewed extended collection binding set changed")
    rows = []
    for name in names:
        text = (directory / (name + "_resource_gen.go")).read_text()
        functions = re.findall(
            r"func (\w+ResourceSchema)\(ctx context.Context\) schema.Schema", text
        )
        if len(functions) != 1:
            raise ValueError("missing/ambiguous official schema function: " + name)
        rows.append("  " + json.dumps(name) + ": generated." + functions[0] + ",")
    return (
        """// Code generated by tools/schema/bindings.py; DO NOT EDIT.
// Registry references only; schemas/models come from the pinned official generators.
// SPDX-License-Identifier: MPL-2.0
package provider
import (
 "context"
 "github.com/hashicorp/terraform-plugin-framework/resource"
 "github.com/hashicorp/terraform-plugin-framework/resource/schema"
 "github.com/matejaputic/terraform-provider-routeros/internal/catalog"
 "github.com/matejaputic/terraform-provider-routeros/internal/generated"
)
func extendedCollectionConstructors() []func() resource.Resource {
 bindings:=map[string]func(context.Context) schema.Schema{
"""
        + "\n".join(rows)
        + """
 }
 result:=[]func() resource.Resource{}
 for _,policy:=range catalog.ExtendedCollections() {
  result=append(result,func()resource.Resource{return newCollection(policy,bindings[policy.Name](context.Background()))})
 }
 return result
}
"""
    )


if __name__ == "__main__":
    try:
        Path(sys.argv[2]).write_text(generate(Path(sys.argv[1])))
    except (OSError, ValueError, IndexError) as e:
        print("binding-failure: " + str(e), file=sys.stderr)
        sys.exit(1)
