// Code generated by tools/schema/additional_settings_bindings.py; DO NOT EDIT.
// Registry references only: all schemas/models come from the official generators.
// SPDX-License-Identifier: MPL-2.0
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/matejaputic/terraform-provider-routeros/internal/catalog"
	"github.com/matejaputic/terraform-provider-routeros/internal/generated"
)

func additionalSettingsConstructors() []func() resource.Resource {
	bindings := map[string]func(context.Context) schema.Schema{
		"capsman_aaa":               generated.CapsmanAaaResourceSchema,
		"capsman_manager":           generated.CapsmanManagerResourceSchema,
		"container_config":          generated.ContainerConfigResourceSchema,
		"disk_settings":             generated.DiskSettingsResourceSchema,
		"ip_dns":                    generated.IpDnsResourceSchema,
		"interface_detect_internet": generated.InterfaceDetectInternetResourceSchema,
		"interface_l2tp_server":     generated.InterfaceL2tpServerResourceSchema,
		"interface_sstp_server":     generated.InterfaceSstpServerResourceSchema,
		"interface_wireless_cap":    generated.InterfaceWirelessCapResourceSchema,
		"ip_cloud":                  generated.IpCloudResourceSchema,
		"ip_cloud_advanced":         generated.IpCloudAdvancedResourceSchema,
		"ip_smb":                    generated.IpSmbResourceSchema,
		"ip_ssh_server":             generated.IpSshServerResourceSchema,
		"ppp_aaa":                   generated.PppAaaResourceSchema,
		"snmp":                      generated.SnmpResourceSchema,
		"system_clock":              generated.SystemClockResourceSchema,
		"system_led_settings":       generated.SystemLedSettingsResourceSchema,
		"system_user_settings":      generated.SystemUserSettingsResourceSchema,
		"tool_bandwidth_server":     generated.ToolBandwidthServerResourceSchema,
		"tool_email":                generated.ToolEmailResourceSchema,
		"ip_upnp":                   generated.IpUpnpResourceSchema,
		"system_user_aaa":           generated.SystemUserAaaResourceSchema,
		"user_manager_advanced":     generated.UserManagerAdvancedResourceSchema,
		"user_manager_database":     generated.UserManagerDatabaseResourceSchema,
		"user_manager_settings":     generated.UserManagerSettingsResourceSchema,
		"wifi_cap":                  generated.WifiCapResourceSchema,
		"wifi_capsman":              generated.WifiCapsmanResourceSchema,
	}
	result := []func() resource.Resource{}
	for _, policy := range catalog.AdditionalSettings() {
		result = append(result, func() resource.Resource { return newSingleton(policy, bindings[policy.Name](context.Background())) })
	}
	return result
}
