// Code generated by tools/schema/bindings.py; DO NOT EDIT.
// Registry references only; schemas/models come from the pinned official generators.
// SPDX-License-Identifier: MPL-2.0
package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/matejaputic/terraform-provider-routeros/internal/catalog"
	"github.com/matejaputic/terraform-provider-routeros/internal/generated"
)

func batchACollectionConstructors() []func() resource.Resource {
	bindings := map[string]func(context.Context) schema.Schema{
		"system_certificate_scep_server":  generated.SystemCertificateScepServerResourceSchema,
		"ip_dhcp_client":                  generated.IpDhcpClientResourceSchema,
		"ip_dhcp_server_option_matcher":   generated.IpDhcpServerOptionMatcherResourceSchema,
		"ip_dhcp_server_option_set":       generated.IpDhcpServerOptionSetResourceSchema,
		"ip_dns_adlist":                   generated.IpDnsAdlistResourceSchema,
		"ip_vrf":                          generated.IpVrfResourceSchema,
		"ipv6_address":                    generated.Ipv6AddressResourceSchema,
		"ipv6_dhcp_client":                generated.Ipv6DhcpClientResourceSchema,
		"ipv6_dhcp_client_option":         generated.Ipv6DhcpClientOptionResourceSchema,
		"ipv6_firewall_addr_list":         generated.Ipv6FirewallAddrListResourceSchema,
		"ipv6_firewall_filter":            generated.Ipv6FirewallFilterResourceSchema,
		"ipv6_neighbor_discovery":         generated.Ipv6NeighborDiscoveryResourceSchema,
		"ipv6_route":                      generated.Ipv6RouteResourceSchema,
		"interface_6to4":                  generated.Interface6to4ResourceSchema,
		"interface_bonding":               generated.InterfaceBondingResourceSchema,
		"interface_bridge_vlan":           generated.InterfaceBridgeVlanResourceSchema,
		"interface_dot1x_client":          generated.InterfaceDot1xClientResourceSchema,
		"interface_dot1x_server":          generated.InterfaceDot1xServerResourceSchema,
		"interface_gre6":                  generated.InterfaceGre6ResourceSchema,
		"interface_l2tp_client":           generated.InterfaceL2tpClientResourceSchema,
		"interface_macvlan":               generated.InterfaceMacvlanResourceSchema,
		"interface_ovpn_server":           generated.InterfaceOvpnServerResourceSchema,
		"interface_pppoe_client":          generated.InterfacePppoeClientResourceSchema,
		"interface_pppoe_server":          generated.InterfacePppoeServerResourceSchema,
		"interface_sstp_client":           generated.InterfaceSstpClientResourceSchema,
		"interface_veth":                  generated.InterfaceVethResourceSchema,
		"interface_vxlan":                 generated.InterfaceVxlanResourceSchema,
		"interface_vxlan_vteps":           generated.InterfaceVxlanVtepsResourceSchema,
		"interface_wireguard":             generated.InterfaceWireguardResourceSchema,
		"interface_wireguard_peer":        generated.InterfaceWireguardPeerResourceSchema,
		"ip_dns_forwarders":               generated.IpDnsForwardersResourceSchema,
		"ip_firewall_layer7_protocol":     generated.IpFirewallLayer7ProtocolResourceSchema,
		"ip_hotspot":                      generated.IpHotspotResourceSchema,
		"ip_hotspot_ip_binding":           generated.IpHotspotIpBindingResourceSchema,
		"ip_hotspot_profile":              generated.IpHotspotProfileResourceSchema,
		"ip_hotspot_user":                 generated.IpHotspotUserResourceSchema,
		"ip_hotspot_user_profile":         generated.IpHotspotUserProfileResourceSchema,
		"ip_hotspot_walled_garden":        generated.IpHotspotWalledGardenResourceSchema,
		"ip_hotspot_walled_garden_ip":     generated.IpHotspotWalledGardenIpResourceSchema,
		"ip_ipsec_identity":               generated.IpIpsecIdentityResourceSchema,
		"ip_ipsec_mode_config":            generated.IpIpsecModeConfigResourceSchema,
		"ip_ipsec_peer":                   generated.IpIpsecPeerResourceSchema,
		"ip_ipsec_policy":                 generated.IpIpsecPolicyResourceSchema,
		"ip_ipsec_policy_group":           generated.IpIpsecPolicyGroupResourceSchema,
		"ip_ipsec_profile":                generated.IpIpsecProfileResourceSchema,
		"ip_ipsec_proposal":               generated.IpIpsecProposalResourceSchema,
		"ip_tftp":                         generated.IpTftpResourceSchema,
		"ip_traffic_flow_target":          generated.IpTrafficFlowTargetResourceSchema,
		"ipv6_dhcp_server":                generated.Ipv6DhcpServerResourceSchema,
		"ipv6_dhcp_server_option":         generated.Ipv6DhcpServerOptionResourceSchema,
		"ipv6_dhcp_server_option_sets":    generated.Ipv6DhcpServerOptionSetsResourceSchema,
		"ipv6_nd_prefix":                  generated.Ipv6NdPrefixResourceSchema,
		"ipv6_pool":                       generated.Ipv6PoolResourceSchema,
		"ip_nat_pmp_interfaces":           generated.IpNatPmpInterfacesResourceSchema,
		"interface_ovpn_client":           generated.InterfaceOvpnClientResourceSchema,
		"ppp_profile":                     generated.PppProfileResourceSchema,
		"ppp_secret":                      generated.PppSecretResourceSchema,
		"queue_simple":                    generated.QueueSimpleResourceSchema,
		"queue_tree":                      generated.QueueTreeResourceSchema,
		"queue_type":                      generated.QueueTypeResourceSchema,
		"radius":                          generated.RadiusResourceSchema,
		"routing_bfd_configuration":       generated.RoutingBfdConfigurationResourceSchema,
		"routing_bgp_connection":          generated.RoutingBgpConnectionResourceSchema,
		"routing_bgp_evpn":                generated.RoutingBgpEvpnResourceSchema,
		"routing_bgp_instance":            generated.RoutingBgpInstanceResourceSchema,
		"routing_bgp_template":            generated.RoutingBgpTemplateResourceSchema,
		"routing_bgp_vpn":                 generated.RoutingBgpVpnResourceSchema,
		"routing_filter_rule":             generated.RoutingFilterRuleResourceSchema,
		"routing_id":                      generated.RoutingIdResourceSchema,
		"routing_igmp_proxy_interface":    generated.RoutingIgmpProxyInterfaceResourceSchema,
		"routing_ospf_area":               generated.RoutingOspfAreaResourceSchema,
		"routing_ospf_area_range":         generated.RoutingOspfAreaRangeResourceSchema,
		"routing_ospf_instance":           generated.RoutingOspfInstanceResourceSchema,
		"routing_ospf_interface_template": generated.RoutingOspfInterfaceTemplateResourceSchema,
		"routing_rule":                    generated.RoutingRuleResourceSchema,
		"snmp_community":                  generated.SnmpCommunityResourceSchema,
		"system_logging":                  generated.SystemLoggingResourceSchema,
		"system_scheduler":                generated.SystemSchedulerResourceSchema,
		"tool_graphing_interface":         generated.ToolGraphingInterfaceResourceSchema,
		"tool_graphing_queue":             generated.ToolGraphingQueueResourceSchema,
		"tool_graphing_resource":          generated.ToolGraphingResourceResourceSchema,
		"tool_netwatch":                   generated.ToolNetwatchResourceSchema,
		"ip_upnp_interfaces":              generated.IpUpnpInterfacesResourceSchema,
		"system_user":                     generated.SystemUserResourceSchema,
		"system_user_group":               generated.SystemUserGroupResourceSchema,
		"system_user_sshkeys":             generated.SystemUserSshkeysResourceSchema,
	}
	result := []func() resource.Resource{}
	for _, policy := range catalog.BatchACollections() {
		result = append(result, func() resource.Resource { return newCollection(policy, bindings[policy.Name](context.Background())) })
	}
	return result
}
